table 'Capex Bookings'
	lineageTag: 68a2a9b8-f860-424f-8db0-1bd1b067d176

	column 'Company Code'
		dataType: string
		lineageTag: 2b40e4ae-d476-4362-a757-61181be623c9
		summarizeBy: none
		sourceColumn: Company Code

		annotation SummarizationSetBy = Automatic

	column 'Document Number'
		dataType: string
		lineageTag: 689bda29-67b2-455c-957e-d1046948c114
		summarizeBy: none
		sourceColumn: Document Number

		annotation SummarizationSetBy = Automatic

	column 'Document Date'
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: 833eb856-b2b7-480e-a4f5-19bcd3d7338f
		summarizeBy: none
		sourceColumn: Document Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Posting Key'
		dataType: string
		lineageTag: a24e49f2-6fea-459e-bb16-29fea1dfb4ac
		summarizeBy: none
		sourceColumn: Posting Key

		annotation SummarizationSetBy = Automatic

	column 'Posting Date'
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: a725bb2a-0522-48d3-8226-5fc9f4de5a10
		summarizeBy: none
		sourceColumn: Posting Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Booking Text'
		dataType: string
		lineageTag: cf9f6297-7dc7-406c-a79b-2967c456cc8b
		summarizeBy: none
		sourceColumn: Booking Text

		annotation SummarizationSetBy = Automatic

	column Assignment
		dataType: string
		lineageTag: 73df81c1-0304-4077-9580-fb365df60a70
		summarizeBy: none
		sourceColumn: Assignment

		annotation SummarizationSetBy = Automatic

	column Item
		dataType: string
		lineageTag: eee501e1-ad21-41d5-a2f8-8874ec0f6bef
		summarizeBy: none
		sourceColumn: Item

		annotation SummarizationSetBy = Automatic

	column 'Tax Code'
		dataType: string
		lineageTag: 09641313-f3a9-4ea1-ac7e-66f50daa5a9f
		summarizeBy: none
		sourceColumn: Tax Code

		annotation SummarizationSetBy = Automatic

	column 'Offsetting acct no.'
		dataType: string
		lineageTag: 64278c08-87b5-42a9-af6a-5590762f5265
		summarizeBy: none
		sourceColumn: Offsetting acct no.

		annotation SummarizationSetBy = Automatic

	column Account
		dataType: string
		lineageTag: 528640ec-51fe-46a1-b3a2-a60a364c4497
		summarizeBy: none
		sourceColumn: Account

		annotation SummarizationSetBy = Automatic

	column 'Cost Center'
		dataType: string
		lineageTag: 056e4e2d-c61c-4e4e-beb1-055f4892c9ff
		summarizeBy: none
		sourceColumn: Cost Center

		annotation SummarizationSetBy = Automatic

	column 'Debit/Credit Ind.'
		dataType: string
		lineageTag: 64718e4c-f7ca-400e-8c1a-88163cc3db18
		summarizeBy: none
		sourceColumn: Debit/Credit Ind.

		annotation SummarizationSetBy = Automatic

	column 'Reversed with'
		dataType: string
		lineageTag: 25685a93-d8b5-4efa-bf51-4c36003da8e4
		summarizeBy: none
		sourceColumn: Reversed with

		annotation SummarizationSetBy = Automatic

	column 'Reference Key 1'
		dataType: string
		lineageTag: c02e813f-ee04-427e-b5e1-5303b9761d2b
		summarizeBy: none
		sourceColumn: Reference Key 1

		annotation SummarizationSetBy = Automatic

	column 'Reference Key 2'
		dataType: string
		lineageTag: ab4f6e5c-4893-4d61-b362-e02d097c1016
		summarizeBy: none
		sourceColumn: Reference Key 2

		annotation SummarizationSetBy = Automatic

	column Asset
		dataType: string
		lineageTag: f29ab6d7-4b19-40d4-80f8-a6b9cfc34cfe
		summarizeBy: none
		sourceColumn: Asset

		annotation SummarizationSetBy = Automatic

	column 'Asset Subnumber'
		dataType: string
		lineageTag: cb40f758-232b-400c-b06f-65698cf56ca7
		summarizeBy: none
		sourceColumn: Asset Subnumber

		annotation SummarizationSetBy = Automatic

	column Order
		dataType: string
		lineageTag: d786c73f-0f99-4f9c-a70e-4eafcbc93d64
		summarizeBy: none
		sourceColumn: Order

		annotation SummarizationSetBy = Automatic

	column 'WBS element'
		dataType: string
		lineageTag: 9d19ca6c-d3e1-47ab-b230-4376b3777563
		summarizeBy: none
		sourceColumn: WBS element

		annotation SummarizationSetBy = Automatic

	column 'Time Stamp'
		dataType: dateTime
		formatString: General Date
		lineageTag: 445f46d9-6dc1-4731-8990-2c3cb5a2121a
		summarizeBy: none
		sourceColumn: Time Stamp

		annotation SummarizationSetBy = Automatic

	column 'Profit Center'
		dataType: string
		lineageTag: 2f4d33d9-66db-42b3-b42b-8f4346eba605
		summarizeBy: none
		sourceColumn: Profit Center

		annotation SummarizationSetBy = Automatic

	column 'Amount in EUR'
		dataType: decimal
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 083a81de-d500-4a79-a871-476d5c586203
		summarizeBy: sum
		sourceColumn: Amount in EUR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"de-DE"}

	column 'Asset Number'
		dataType: string
		lineageTag: 2781636f-2588-40f1-b86e-9ea19075c44d
		summarizeBy: none
		sourceColumn: Asset Number

		annotation SummarizationSetBy = Automatic

	column 'Asset Number Country'
		dataType: string
		lineageTag: 58114aac-0250-4e1f-9abf-bda74d351136
		summarizeBy: none
		sourceColumn: Asset Number Country

		annotation SummarizationSetBy = Automatic

	column 'Month Date'
		dataType: dateTime
		formatString: dd.mm.yyyy
		lineageTag: 21b108f4-6187-4a25-bf58-ebc2d7d4a93d
		summarizeBy: none
		sourceColumn: Month Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Test = RELATED('Asset List'[Asset Number and Name])
		lineageTag: c2b0e574-a407-4ee5-840b-4500bff5cc30
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Capex Bookings' = m
		mode: import
		queryGroup: 07_CAPEX
		source =
				let
				    // SPEED TIP: Read only metadata first
				    SP = SharePoint.Files("https://allianzms.sharepoint.com/teams/AT0090-2759670/pbi/", [ApiVersion = 15]),
				
				    // Filter early
				    Filtered = Table.SelectRows(
				        SP,
				        each Text.Contains([Folder Path], "/04_Capex/")
				            and Text.Contains([Name], "postings") and Text.Contains([Name], "Q")
				    ),
				
				    // Buffer list of files → avoids re-scanning SharePoint
				    Files = Table.Buffer(Filtered),
				
				    // Keep only required columns
				    KeepCols = Table.SelectColumns(
				        Files,
				        {"Content", "Name", "Date modified"}
				    ),
				
				    // Function to read each Excel file quickly
				    ReadExcel = (binary as binary) =>
				        let
				            WB   = Excel.Workbook(binary, null, true),
				            Sheet = WB{[Item="Sheet1", Kind="Sheet"]}[Data],
				            Promote = Table.PromoteHeaders(Sheet, [PromoteAllScalars = true])
				        in
				            Promote,
				
				    // Expand by reading each file only once
				    Expanded = Table.AddColumn(Files, "Data", each ReadExcel([Content]), type table),
				
				    Combined = Table.ExpandTableColumn(Expanded, "Data", Table.ColumnNames(Expanded[Data]{0})),
				
				    // Add consistent File / Refresh columns
				    AddMeta =
				        Table.AddColumn(
				            Table.AddColumn(Combined, "File Name", each [Name]),
				            "Refresh Date",
				            each [Date modified]
				        ),
				
				    Removed = Table.RemoveColumns(AddMeta, {"Content", "Name", "Date modified"}),
				    #"Filtered Rows" = Table.SelectRows(Removed, each ([Company Code] <> "")),
				    #"Changed column type" = Table.TransformColumnTypes(#"Filtered Rows", {{"Company Code", type text}, {"Document Number", type text}, {"Document Date", type text}, {"Posting Key", type text}, {"Amount in local currency", type text}, {"Local Currency", type text}, {"Posting Date", type text}, {"Trading partner", type text}, {"Text", type text}, {"Assignment", type text}, {"Item", type text}, {"Tax Code", type text}, {"Offsetting acct no.", type text}, {"Posting Period", type text}, {"Year/month", type text}, {"Account", type text}, {"Cost Element", type text}, {"Cost Center", type text}, {"Debit/Credit Ind.", type text}, {"Reversed with", type text}, {"Reference Key 1", type text}, {"Reference Key 2", type text}, {"Asset", type text}, {"Asset Subnumber", type text}, {"Order", type text}, {"WBS element", type text}, {"Time Stamp", type text}, {"Profit Center", type text}, {"Amount in loc.curr.2", type text}, {"Local Currency 2", type text}, {"File Name", type text}, {"Refresh Date", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed column type",{"Extension", "Date accessed", "Date created", "Attributes", "Folder Path", "File Name", "Refresh Date"}),
				        #"Filtered Rows1" = Table.SelectRows( #"Removed Columns", each ([Document Date] <> null)),
				    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows1",{{"Document Date", type date}}),
				    #"Removed Columns12" = Table.RemoveColumns(#"Changed Type",{"Amount in local currency", "Local Currency", "Trading partner", "Posting Period", "Year/month", "Cost Element"}),
				    #"Filtered Rows12" = Table.SelectRows(#"Removed Columns12", each ([Asset] <> "" and [Asset] <> "*")),
				    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows12",{{"Text", "Booking Text"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"Posting Date", type date}, {"Amount in loc.curr.2", Currency.Type}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type1",{{"Amount in loc.curr.2", "Amount in EUR"}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Time Stamp", type datetime}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type2",{"Local Currency 2"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Columns1", "Asset Number", each [Asset]&"/"&[Asset Subnumber]),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom",{{"Asset Number", type text}}),
				    #"Added Custom1" = Table.AddColumn(#"Changed Type3", "Asset Number Country", each [Company Code]&"-"&[Asset Number]),
				    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "Month Date", each Date.StartOfMonth([Posting Date])),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Added Custom2",{{"Month Date", type date}}),
				    #"Filtered Rows2" = Table.SelectRows(#"Changed Type4", each [Amount in EUR] <> 0),
				    #"Appended Query" = Table.Combine({#"Filtered Rows2", #"Capex Bookings 2024"})
				in
				   #"Appended Query"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

