table 'Group Debtors'
	lineageTag: 35373104-eea1-44bb-8741-bfbd120ce641

	column 'Debtor Number'
		dataType: string
		lineageTag: db26baa6-64a5-4f5f-afb9-656bd760de04
		summarizeBy: none
		sourceColumn: Debtor Number

		annotation SummarizationSetBy = Automatic

	column 'Debtor Name'
		dataType: string
		lineageTag: 5612709d-3143-4836-a0de-d62464730f71
		summarizeBy: none
		sourceColumn: Debtor Name

		annotation SummarizationSetBy = Automatic

	partition 'Group Debtors' = m
		mode: import
		queryGroup: '05_SAP BAP'
		source =
				let
				    Source = SharePoint.Files("https://allianzms.sharepoint.com/teams/DE1214-6208581/", [ApiVersion = 15]),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Folder Path] = "https://allianzms.sharepoint.com/teams/DE1214-6208581/Shared Documents/PRICING/02_Price Lists/2025 price lists/") and ([Extension] = ".xlsx" or [Extension] = ".XLSX")),
				    #"Filtered Rows2" = Table.SelectRows(#"Filtered Rows", each Text.Contains([Name], "price")),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows2", let latest = List.Max(#"Filtered Rows2"[Date created]) in each [Date created] = latest),
				    #"Added Custom" = Table.AddColumn(#"Filtered Rows1", "Extracted Data", each Table.SelectRows(Excel.Workbook([Content]), each [Item] = "Active Debtors")),
				    #"Removed Other Columns2" = Table.SelectColumns(#"Added Custom",{"Extracted Data"}),
				    #"Expanded Extracted Data" = Table.ExpandTableColumn(#"Removed Other Columns2", "Extracted Data", {"Data"}, {"Extracted Data.Data"}),
				    #"Expanded Extracted Data.Data" = Table.ExpandTableColumn(#"Expanded Extracted Data", "Extracted Data.Data", {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22"}, {"Extracted Data.Data.Column1", "Extracted Data.Data.Column2", "Extracted Data.Data.Column3", "Extracted Data.Data.Column4", "Extracted Data.Data.Column5", "Extracted Data.Data.Column6", "Extracted Data.Data.Column7", "Extracted Data.Data.Column8", "Extracted Data.Data.Column9", "Extracted Data.Data.Column10", "Extracted Data.Data.Column11", "Extracted Data.Data.Column12", "Extracted Data.Data.Column13", "Extracted Data.Data.Column14", "Extracted Data.Data.Column15", "Extracted Data.Data.Column16", "Extracted Data.Data.Column17", "Extracted Data.Data.Column18", "Extracted Data.Data.Column19", "Extracted Data.Data.Column20", "Extracted Data.Data.Column21", "Extracted Data.Data.Column22"}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Expanded Extracted Data.Data", [PromoteAllScalars=true]),
				    #"Renamed Columns" = Table.RenameColumns(#"Promoted Headers",{{"Customer", "Debtor Number"}, {"Name 1", "Debtor Name"}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns",{"Debtor Number", "Debtor Name"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns")
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

