table 'Rate Cards Translation'
	lineageTag: 9ce192b4-6187-4a71-82aa-46e9aef69f85

	column 'User Rate Card PPM'
		dataType: string
		lineageTag: 04600abb-168d-4e55-9cec-c93ef8cf77f9
		summarizeBy: none
		sourceColumn: User Rate Card PPM

		annotation SummarizationSetBy = Automatic

	column 'User Rate Card Price List'
		dataType: string
		lineageTag: 59755cf0-e0d5-4091-bae5-11dfbafce16a
		summarizeBy: none
		sourceColumn: User Rate Card Price List

		annotation SummarizationSetBy = Automatic

	partition 'Rate Cards Translation' = m
		mode: import
		queryGroup: '01_Master Domain Data'
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://allianzms.sharepoint.com/teams/AT0090-2759670/pbi/Shared%20Documents/01_Power%20BI/Data%20Sources/00_Master%20Data/Master%20Domain%20Data.xlsx"), null, true),
				    GradeandProficiencyLevels_Table = Source{[Item="RateCardsTranslation",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(GradeandProficiencyLevels_Table,{{"User Rate Card PPM", type text}, {"User Rate Card Price List", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

